//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLingualConfiguration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLingualConfiguration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        internal static string ChildName_Selection {
            get {
                return ResourceManager.GetString("ChildName_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This configuration parameter enables or disables the functions of this Demo-VAF. For demonstrating the functions just a Windows Event Log Info entry will be written - multi-lingual in the language configured, of course..
        /// </summary>
        internal static string HelpText_Configuration_Enabled {
            get {
                return ResourceManager.GetString("HelpText_Configuration_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you have to select the option for this entry. You really have to do this because it is mandatory, sorry..
        /// </summary>
        internal static string HelpText_SelectedOption {
            get {
                return ResourceManager.GetString("HelpText_SelectedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you select the first entry you will show that you always take the first solution. But please check if it is the best..
        /// </summary>
        internal static string HelpText_SelectionOptions_First {
            get {
                return ResourceManager.GetString("HelpText_SelectionOptions_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second may be better. If you get here you have already compared the possibilities..
        /// </summary>
        internal static string HelpText_SelectionOptions_Second {
            get {
                return ResourceManager.GetString("HelpText_SelectionOptions_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen the third option - please take note of your time if you always compare everything first. This may cause that nothing gets finished..
        /// </summary>
        internal static string HelpText_SelectionOptions_Third {
            get {
                return ResourceManager.GetString("HelpText_SelectionOptions_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add multiple selection in case you cannot decide..
        /// </summary>
        internal static string HelpText_Selections {
            get {
                return ResourceManager.GetString("HelpText_Selections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-lingual VAF active.
        /// </summary>
        internal static string Label_Configuration_Enabled {
            get {
                return ResourceManager.GetString("Label_Configuration_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Option.
        /// </summary>
        internal static string Label_SelectedOption {
            get {
                return ResourceManager.GetString("Label_SelectedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First selection option for this demo.
        /// </summary>
        internal static string Label_SelectionOptions_First {
            get {
                return ResourceManager.GetString("Label_SelectionOptions_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected selection option is invalid..
        /// </summary>
        internal static string Label_SelectionOptions_Invalid {
            get {
                return ResourceManager.GetString("Label_SelectionOptions_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second selection option for this demo.
        /// </summary>
        internal static string Label_SelectionOptions_Second {
            get {
                return ResourceManager.GetString("Label_SelectionOptions_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third selection option for this demo.
        /// </summary>
        internal static string Label_SelectionOptions_Third {
            get {
                return ResourceManager.GetString("Label_SelectionOptions_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selections.
        /// </summary>
        internal static string Label_Selections {
            get {
                return ResourceManager.GetString("Label_Selections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [none].
        /// </summary>
        internal static string Message_No_Selection_Option {
            get {
                return ResourceManager.GetString("Message_No_Selection_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selections list has been changed. The new values are:.
        /// </summary>
        internal static string Message_Selection_Changed {
            get {
                return ResourceManager.GetString("Message_Selection_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VAF has been disabled..
        /// </summary>
        internal static string Message_VAF_Disabled {
            get {
                return ResourceManager.GetString("Message_VAF_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VAF has been enabled..
        /// </summary>
        internal static string Message_VAF_Enabled {
            get {
                return ResourceManager.GetString("Message_VAF_Enabled", resourceCulture);
            }
        }
    }
}
